name = "mahjong"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "mahjong-db"
database_id = "91a51075-b771-416c-a277-4ba8dc4538cd"
migrations_dir = "drizzle"

[vars]
APP_TIMEZONE = "Asia/Tokyo"
